resolver: lts-9.0
packages:
- .
- location:
    git: https://github.com/agrafix/Spock.git
    commit: 7de155844bf264e647d434b9c89c7a013585d30a
  extra-dep: true
  subdirs:
    - Spock
    - Spock-core
    - reroute
extra-deps: []
